#!/bin/bash


sudo wget -O /etc/apt/sources.list.d/newrelic.list http://download.newrelic.com/debian/newrelic.list
sudo apt-key adv --keyserver hkp://subkeys.pgp.net --recv-keys 548C16BF
sudo apt-get update
sudo apt-get install newrelic-sysmond
