#!/bin/bash

set -euxo pipefail

# zsh and pip
sudo apt-get update
sudo apt-get install -y zsh python-pip

sudo apt-get install -y git vim curl lrzip iputils-ping

echo "Setting passwordless sudo..."
sudo bash -c "echo \"$(whoami) ALL=(ALL:ALL) NOPASSWD: ALL\" > /etc/sudoers.d/$(whoami)"

$HOME/dotfiles/deploy/setup-node

