#!/bin/bash

set -uxo

ADD=$(which apt-get)
if [[ -z $ADD ]]; then
    ADD=$(which dnf)
fi
# zsh and pip

sudo $ADD install -y zsh python3-pip
sudo groupadd dev
sudo $ADD install -y git vim curl lrzip iputils-ping

echo "Setting passwordless sudo..."
sudo bash -c "echo \"$(whoami) ALL=(ALL:ALL) NOPASSWD: ALL\" > /etc/sudoers.d/$(whoami)"


