#!/bin/bash

# Check for proper number of command line args.
EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: setup-node <version, like v0.6.14>"
  exit $E_BADARGS
fi

sudo apt-get install -y curl g++ libssl-dev

git clone https://github.com/creationix/nvm.git $HOME/.nvm
. $HOME/.nvm/nvm.sh

VER=${1:-v10}
nvm install $VER
nvm use $VER

echo ". $HOME/.nvm/nvm.sh" >> $HOME/.bashrc
echo "nvm use $VER" >> $HOME/.bashrc

source $HOME/.bashrc

npm i -g cryptsend-cli

