#!/bin/bash

# install docker.
curl -fsSL get.docker.com -o get-docker.sh
sudo sh get-docker.sh
rm get-docker.sh
sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
who=$(whoami)
sudo usermod -aG docker $who
#apply the group to current shell.
newgrp docker
newgrp $who

