#!/bin/bash

sudo add-apt-repository ppa:webupd8team/atom
sudo add-apt-repository ppa:gnome-terminator
#sudo add-apt-repository ppa:webupd8team/sublime-text-3
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

sudo apt-get update

sudo apt-get update
sudo apt-get install -y git vim curl zsh
sudo apt-get install -y i3 xfe autocutsel

mkdir $HOME/.config/i3
cd $HOME/.config/i3 && rm config && ln -s ../../dotfiles/.i3config config

#sudo apt-get install sublime-text-installer
sudo apt-get install -y xbacklight atom google-chrome-stable terminator

cd $HOME/.atom && rm config.cson && ln -s ../dotfiles/config.cson
cd $HOME/.atom && rm styles.less && ln -s ../dotfiles/styles.less
load-atom-packages

