#!/bin/sh

wget https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download
mv uc\?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA gdrive
chmod +x gdrive
sudo install gdrive /usr/local/bin/gdrive
gdrive list -q "name contains 'timesheet'"
