#!/bin/bash

sudo add-apt-repository ppa:gnome-terminator
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

sudo apt-get update

sudo apt-get install -y i3 xfe i3-lock

mkdir $HOME/.config/i3
cd $HOME/.config/i3 && rm config && ln -s ../../dotfiles/.i3config config

sudo apt-get install -y xbacklight google-chrome-stable terminator redshift nitrogen

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install -y code # or code-insiders

cd $HOME && rmdir Documents Pictures Music Public Templates Videos

# performance - remove ubuntu junk
sudo systemctl disable apparmor.service
sudo systemctl disable snapd.autoimport.service
sudo systemctl disable ModemManager.service

# save keystrokes in aptitude.
echo 'APT::Get::Assume-Yes "true";' | sudo tee -a /etc/apt/apt.conf.d/90forceyes
echo 'APT::Get::force-yes "true";' | sudo tee -a /etc/apt/apt.conf.d/90forceyes


