#!/bin/bash

echo "Satchel is a repository filled with standard unix config and scripts for Countable Web Productions."
echo "NOTE: You should probably run this from your home directory."
echo "source $HOME/dotfiles/.bashrc" >> .bashrc
ln -s dotfiles/.vimrc
ln -s dotfiles/.gitconfig
source .bashrc
echo "source $HOME/dotfiles/.zshrc" >> .zshrc
sudo chsh -s /bin/zsh $(whoami)
echo "Done installing dotfiles."

