#!/bin/bash

set -euxo pipefail

echo "************************************************************************************"
echo "Welcome to the Countable dotfiles!"
echo ""
echo "This is a repository filled with standard unixy stuff for Countable Web Productions."
echo "This includes bootstrapping workstations and servers as Jenkins slaves."
echo "If you're doing something repetitive on unix (Mac OS terminal or Linux) automate it, and save it in here!"

cd $HOME

echo "Sourcing the dotfiles .bashrc..."
touch .bashrc
echo "source $HOME/dotfiles/.bashrc" >> .bashrc

echo "Sourcing the dotfiles .zshrc..."
touch .zshrc
echo "source $HOME/dotfiles/.zshrc" >> .zshrc

echo "Linking your .vimrc..."
ln -sf dotfiles/.vimrc
cp $HOME/dotfiles/.gitconfig $HOME/
ln -sf dotfiles/.gitignore

source .bashrc
echo "source $HOME/dotfiles/.zshrc" >> .zshrc
sudo chsh -s /bin/zsh $(whoami)
echo "Done installing dotfiles."

ssh-keygen -f id_rsa -t rsa -N ''

cp "dotfiles/.ssh/config" .ssh/config

echo "setting passwordless sudo"
sudo bash -c "echo \"$(whoami) ALL=(ALL:ALL) NOPASSWD: ALL\" > /etc/sudoers.d/$(whoami)"

